project:
  type: book

book:
  title: "Notas de Introducción a la Inteligencia Artificial"
  author: "Francisco Palm"
  date: "2025-04-30"
  chapters:
    - index.qmd
    - intro.qmd
    - agentes.qmd
    - part: "Búsqueda"
      chapters:
        - espacio-estados.qmd
        - busqueda-no-informada.qmd
        - busqueda-informada.qmd
    - part: "PSR"
      chapters:
        - satisfaccion-restricciones.qmd
        - solucion-psr.qmd
        - filtrado-psr.qmd
        - ordenamiento-psr.qmd
        - busqueda-local.qmd
    - part: "Juegos"
      chapters:
        - juegos.qmd
        - minimax.qmd
    - summary.qmd
    - references.qmd
    - part: "Aprendizaje Automatico"
      chapters:
        - aprendizaje.qmd
        - naive-bayes.qmd
        - perceptron.qmd
        - perceptron-binario.qmd
        - regresion-lineal.qmd
        - optimizacion.qmd
        - regresion-logistica.qmd
        - logistica-multiclase.qmd
        - redes-neuronales.qmd


bibliography: references.bib

format:
  html:
    theme:
      - pulsar
      - brand
    highlight-style: a11y
  pdf:
    documentclass: scrreprt


lang: es
